apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-agent.fullname" . }}
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
data:
  agent.yaml: |
    {{- tpl .Values.config.agent . | nindent 4 }}
  strategies.json: |
    {{- tpl .Values.config.strategies . | nindent 4 }}
